# Generated by Django 2.2.24 on 2021-07-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Mob_No', models.IntegerField()),
                ('Aadhar_No', models.IntegerField()),
                ('Pan_No', models.CharField(max_length=20)),
                ('Current_Address', models.CharField(max_length=50)),
                ('Permanent_Address', models.CharField(max_length=50)),
                ('User_Type', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=30)),
                ('UserName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
