# Generated by Django 2.2.24 on 2021-07-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetails',
            name='Aadhar_No',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='registerdetails',
            name='Email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='registerdetails',
            name='Pan_No',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registerdetails',
            name='UserName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
