# Generated by Django 2.2.24 on 2021-07-10 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterAccount', '0002_auto_20210710_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdetails',
            name='Mob_No',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{0,9}')]),
        ),
    ]
